security:
    encoders:
            #Symfony\Component\Security\Core\User\User: plaintext
            App\Entity\Utilisateur : bcrypt

    role_hierarchy:
                ROLE_ADMIN: ROLE_USER_3
                ROLE_USER3: [ROLE_USER,ROLE_USER_2]


    providers:
            in_bd:
                entity:
                    class: App\Entity\Utilisateur
                    property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            # activate different ways to authenticate

            security: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            provider: in_bd

            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: security_logout
                target: default

            access_denied_url: interdit

            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/Suppression, roles: ROLE_ADMIN }
        - { path: ^/Modification, roles: ROLE_ADMIN}
        - { path: ^/inscription, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN] }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

